# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-25 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='\u540d\u79f0')),
                ('location', models.CharField(max_length=256, verbose_name='\u4f4d\u7f6e')),
            ],
        ),
    ]
